feat: Agrega soporte para exportar el texto o value de un Nodo XML.
phpcfdi/cfdi-to-json pull request #13
Opened 2022-10-01 19:32 UTC by gam04

- Agrega la propiedad `value` en `Node`.
- Agrega la llave de cadena vacia en `Node::toArray()`.
- Asigna `value` sin white-space desde `CfdiToDataNode`.

2022-10-01 23:35 UTC, eclipxe13 requested changes

2022-10-01 23:35 UTC, eclipxe13 commented on src/CfdiToDataNode.php
> +        $value = preg_replace(['/\s+/', '/^ +/', '/ +$/'], [' ', '', ''], implode('', $values));
Creo que es mejor hacer un cast de tipo `return (string) preg_replace(...)` o bien una anotación `/** @var-phpstan string $value */` para evitar la siguiente comparación y el `RuntimeException`.
Supongo que de no hacerlo PHPStan se quejaba, cierto?

2022-10-01 23:35 UTC, eclipxe13 commented on src/Nodes/Node.php
> +        $array = $this->attributes + $this->children->toArray();
De esta forma el orden de construcción mandará al contenido del texto siempre hasta al final, no sería mejor algo como:
```php
$textArray = ('' !== $this->getValue()) ? ['' => $this->getValue()] : [];
return $textArray + $this->attributes + $this->children->toArray();
```
Y así se vería como:
```json
{
  "Node": {
    "": "Contenido de texto",
    "Attribute": "foo",
    "Child": {}
  }
}
```

2022-10-02 00:16 UTC, gam04 commented on src/CfdiToDataNode.php
> +        $value = preg_replace(['/\s+/', '/^ +/', '/ +$/'], [' ', '', ''], implode('', $values));
Si, se puso estricto con la salida de `preg_replace` .
En este caso, supongo que no hay manera de que falle `preg_replace` (y por lo tanto regrese null) ya que la regex es correcta, ¿no?

2022-10-02 00:20 UTC, gam04 commented on src/Nodes/Node.php
> +        $array = $this->attributes + $this->children->toArray();
Tenía el dilema sobre el orden, pero creo que se ve mejor como el primero. 👍

2022-10-02 01:02 UTC, eclipxe13 approved these changes

2022-10-02 01:03 UTC, merged